#!/usr/bin/env bash
#
# open-pr.sh — STEP 4: commit CodeMender's fix to a branch, push it to the
# fork, and open a Pull Request whose body is CodeMender's own analysis.
#
# Does NOT touch CodeMender state — only git + the GitHub API — so it needs no
# gcsfuse mount. Reads the metadata that fix.sh left in $WORKSPACE.
set -euo pipefail

WORKSPACE="${WORKSPACE:-/workspace}"
REPO_DIR="${REPO_DIR:-$WORKSPACE/repo}"
BASE_BRANCH="${BASE_BRANCH:-master}"
GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-codemender-bot}"
GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-codemender-bot@users.noreply.github.com}"

: "${GH_OWNER:?set GH_OWNER}"; : "${GH_REPO:?set GH_REPO}"; : "${GH_TOKEN:?set GH_TOKEN (from Secret Manager)}"
# Secret values often carry a trailing newline; strip all whitespace so it
# can't corrupt the push URL or the auth header.
GH_TOKEN=$(printf '%s' "$GH_TOKEN" | tr -d '[:space:]')

STATUS=$(cat "$WORKSPACE/cm-status.txt" 2>/dev/null || echo UNKNOWN)
if [[ "$STATUS" != "FIXED" ]]; then
  echo "cm-status is '$STATUS' (not FIXED) — nothing to open a PR for."; exit 0
fi

# --- Read the finding metadata ----------------------------------------------
F="$WORKSPACE/cm-finding.json"
FID=$(jq -r '.FindingID' "$F")
TITLE=$(jq -r '.Title' "$F")
SEV=$(jq -r '.Severity|ascii_upcase' "$F")
CWE=$(jq -r '.VulnID // "CWE-unknown"' "$F")
VTYPE=$(jq -r '.VulnType // "Vulnerability"' "$F")
CONF=$(jq -r '.Confidence // 0' "$F")
FILE=$(jq -r '.FilePath' "$F" | sed "s#^$REPO_DIR/##")
ANALYSIS=$(jq -r '.Analysis // ""' "$F")
SUMMARY=$(cat "$WORKSPACE/cm-summary.txt")

SHORT="${FID:0:8}"
CWE_SLUG=$(echo "$CWE" | tr 'A-Z' 'a-z' | tr -cd 'a-z0-9-')
BRANCH="codemender/${CWE_SLUG}-${SHORT}"
PR_TITLE="security: fix ${VTYPE} in ${FILE} (${CWE})"

# --- Commit ------------------------------------------------------------------
cd "$REPO_DIR"
git config user.name  "$GIT_AUTHOR_NAME"
git config user.email "$GIT_AUTHOR_EMAIL"
git checkout -b "$BRANCH"
git add -u                                   # tracked modifications only
git commit -F - <<EOF
${PR_TITLE}

${SUMMARY}

Finding:  ${TITLE}
Severity: ${SEV}   Confidence: ${CONF}%   ${CWE}
Detected & remediated by CodeMender (finding ${FID}).
EOF

# --- Push (token redacted from any output) ----------------------------------
PUSH_URL="https://x-access-token:${GH_TOKEN}@github.com/${GH_OWNER}/${GH_REPO}.git"
set +e
PUSH_OUT=$(git push "$PUSH_URL" "$BRANCH" 2>&1); PUSH_RC=$?
set -e
echo "${PUSH_OUT//${GH_TOKEN}/***}"
[[ $PUSH_RC -eq 0 ]] || { echo "❌ git push failed"; exit 1; }

# --- Compose the PR body -----------------------------------------------------
{
  echo "## 🛡️ CodeMender automated security fix"
  echo
  echo "> ${SUMMARY}"
  echo
  echo "| | |"
  echo "|---|---|"
  echo "| **Finding** | ${TITLE} |"
  echo "| **Severity** | ${SEV} |"
  echo "| **Type** | ${VTYPE} (${CWE}) |"
  echo "| **Confidence** | ${CONF}% |"
  echo "| **File** | \`${FILE}\` |"
  echo
  echo "### Analysis"
  echo
  echo "${ANALYSIS}"
  echo
  echo "### Change"
  echo '```diff'
  git --no-pager diff "${BASE_BRANCH}..${BRANCH}" -- "$FILE"
  echo '```'
  echo
  echo "---"
  echo "_Generated by CodeMender. Review the diff before approving; merging applies the fix to \`${BASE_BRANCH}\`._"
} > "$WORKSPACE/cm-pr-body.md"

# --- Open the PR -------------------------------------------------------------
jq -n --arg t "$PR_TITLE" --arg h "$BRANCH" --arg b "$BASE_BRANCH" \
      --rawfile body "$WORKSPACE/cm-pr-body.md" \
      '{title:$t, head:$h, base:$b, body:$body, maintainer_can_modify:true}' > "$WORKSPACE/pr-request.json"

HTTP=$(curl -sS -o "$WORKSPACE/pr-response.json" -w '%{http_code}' -X POST \
  -H "Authorization: Bearer ${GH_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/pulls" \
  -d @"$WORKSPACE/pr-request.json")

if [[ "$HTTP" == "201" ]]; then
  echo "✅ Pull Request opened: $(jq -r '.html_url' "$WORKSPACE/pr-response.json")"
elif [[ "$HTTP" == "422" ]]; then
  echo "ℹ️  A PR for this branch already exists (HTTP 422):"
  jq -r '.errors[]?.message // .message' "$WORKSPACE/pr-response.json"
else
  echo "❌ GitHub API returned HTTP $HTTP"
  jq -r '.message' "$WORKSPACE/pr-response.json" 2>/dev/null || cat "$WORKSPACE/pr-response.json"
  exit 1
fi
